### ISSUE TITLE
Miscellaneous issues with dana-simulator

### ISSUE THREAD

**Issue by marionbarker** [bastiaanv/dana-simulator#2]
I am finding the dana-simulator stays around even after I hit control C.
I reboot my rPi to free up the Bluetooth indication from dana-simulator.

The simulator does not seem to respond to bolus commands properly. After I bolus, the app indicates that pump is not available because it is bolusing.

For example, when running closed loop, if glucose is dropping (so temp basal values are used), I get and keep a green loop.
When glucose is rising, so closed loop issues a bolus, then I get a red loop.

Using feat/dana branch commit 13dfdec2

**Comment by bastiaanv** [comment]
Hi @marionbarker 

I just made several commits containing the following:
- Add support for pump limit sync (https://github.com/nightscout/Trio/pull/266)
- Fix the bolus issue

Could you try again please? 
commit hash simulator: d776ba6

**Comment by bastiaanv** [comment]
I havent been able to reproduce the control + C issue. Do you build the app or do you run it via `go run .`?

**Comment by marionbarker** [comment]
I am running via `go run .`

### Status
Updated simulator to commit: d776ba6 (HEAD -> master, origin/master, origin/HEAD) fix: Hotfixes bolus
Updated feat/dana to commit: f24959d1 (HEAD -> bast-feat/dana, bast/feat/dana) fix: Update danakit & Add DanaPumpManager to staticPumpManagers

Connect to DanaRS and successfully bolus 2 times in a row. - Thanks for the fix.

Delete the Dana pump in the app.
The main screen shows No Insulin. 
Tapping on Settings-> Pump shows Dana i/RS is still selected but not connected - however, rPi acts like it is still talking to a pump.
Trying scanning again  and it reconnects to the rPi.
* able to bolus again

I think deleting the pump should completely delete the pump.
Going to link this comment to Trio PR 266.

**Comment by bastiaanv** [comment]
@marionbarker I've looked into the delete issue, but haven't been able to reproduce it.

Trio version:
```bash
commit 90e34b10cfd3e70f5ef1d8d7ea06a8841b87bd71 (HEAD -> feat/dana, origin/feat/dana)
Author: bastiaanv <bastiankpn7800@gmail.com>
Date:   Sun Jun 16 18:24:31 2024 +0200

    update loopkit
```

The only thing I've found, is that the pump wouldn't let itself be deleted during a bolus. But that is good behaviour if you ask me :)

**Comment by marionbarker** [comment]
Sorry. I meant to circle back to this and close this issue. 

Pretty sure this was a fixed in Trio code. I tested the latest dana rPi simulator yesterday with Trio alpha and the simulator and Trio behaved as expected.
